modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "LicenseRef-Custom"
showAsResourcePack = false
issueTrackerURL = "https://discord.kohara.xyz/"

[[mods]]
	modId = "stellarity" 
	version = "3.0.0"
	displayName = "Stellarity"
	displayURL = "https://modrinth.com/datapack/stellarity"
	description = '''
	Extreme rehaul and expansion of The End!
	'We have End Update at home.'
	'''
	logoFile = "pack.png"
	logoBlur = false
	updateJSONURL = "https://api.modrinth.com/updates/bZgeDzN8/forge_updates.json"
	credits="misode, Bush_King, Brokenemp, Phoenix, Hex"
	authors = "kohara"

[[dependencies.stellarity]]
	modId="neoforge"
	mandatory=false
	versionRange="[20.2,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.stellarity]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.21,1.21]"
	ordering="NONE"
	side="BOTH"